sudo: required
services:
  - docker

before_install:
  - docker build -t robihdy/docker-example -f Dockerfile.dev .

script:
  - docker run robihdy/docker-example npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-example"
  env: "DockerExample-env"
  bucket_name: "elasticbeanstalk-us-east-1-353969886337"
  bucket_path: "docker-example"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY